# jekyll s -b /7781 -H 192.168.178.28 -P 8081
TZ: Europe/Berlin
baseurl: /7781/
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 4
paginate_path: "/zeitmaschine/seite:num/"
collections:
  schulzeit:
    output: true
    order:
    - unsere-schule.md
    - rechnen-schreiben-lesen.md
  fernsehen:
    output: true
    order:
    - das-fernsehprogramm.md
    - neuheiten.md
taglist: 5